### LIBRARY

In [1]:
import pandas as pd
import requests
import json
import math

### SET UP THE ENVIRONMENT

In [2]:
HEADERS = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0",
    "Accept-Language": 'en-US,en;q=0.9',
    "Accept-Encoding": "gzip, deflate, br, zstd",
    "Referer": "https://tiki.vn/",
    "From": "",
    "af-ac-enc-dat": "",
    "x-api-source": "pc"
}

In [3]:
URL = "https://api.tiki.vn/raiden/v2/menu-config?platform=desktop"

In [4]:
response = requests.get(URL, headers=HEADERS)

if response.status_code == 200:
    data = response.json()
    print("Success to fetch data.")
else:
    print("Failed to fetch data:", response.status_code)

Success to fetch data.

### RETRIEVE GROUP ID

In [5]:
groups = data["menu_block"]["items"]
group_list = []

for group in groups:
    text = group["text"]
    link = group["link"]
    # Extract category ID from the link
    group_id = link.split("/")[-1][1:]  
    group_list.append([group_id, text])

groups = pd.DataFrame(group_list, columns=["Group_ID", "Group_Name"])
groups

   Group_ID                        Group_Name
0      8322                     Nhà Sách Tiki
1      1883                Nhà Cửa - Đời Sống
2      1789        Điện Thoại - Máy Tính Bảng
3      2549                 Đồ Chơi - Mẹ & Bé
4      1815         Thiết Bị Số - Phụ Kiện Số
5      1882                     Điện Gia Dụng
6      1520                Làm Đẹp - Sức Khỏe
7      8594            Ô Tô - Xe Máy - Xe Đạp
8       931                     Thời trang nữ
9      4384                   Bách Hóa Online
10     1975               Thể Thao - Dã Ngoại
11      915                    Thời trang nam
12    17166       Cross Border - Hàng Quốc Tế
13     1846  Laptop - Máy Vi Tính - Linh kiện
14     1686                    Giày - Dép nam
15     4221               Điện Tử - Điện Lạnh
16     1703                     Giày - Dép nữ
17     1801           Máy Ảnh - Máy Quay Phim
18    27498               Phụ kiện thời trang
19    44792                              NGON
20     8371              Đồng hồ và Trang sức
21     6000                      Balo và Vali
22    11312                 Voucher - Dịch vụ
23      976                 Túi thời trang nữ
24    27616                Túi thời trang nam

### RETRIEVE THE TOTAL NUMBER OF ITEM FOR EACH GROUP

In [6]:
# Fetch total number of items for each group
for index, row in groups.iterrows():
    group_id = row['Group_ID']
    group_name = row['Group_Name']
    url = "https://tiki.vn/api/personalish/v1/blocks/listings"
    params = {"category": group_id, "page": 1}
    response = requests.get(url, headers=HEADERS, params=params)
    if response.status_code == 200:
        data = response.json()
        total = data.get("paging", {}).get("total", 0)
        per_page = data.get("paging", {}).get("per_page", 0)
        last_page = data.get("paging", {}).get("last_page", 0)
        # # Count total units sold for all items in the group
        # total_units_sold = sum(item.get("quantity_sold", {}).get("value", 0) for item in data.get("data", []))
        num_pages = math.ceil(total / per_page)
        print(f"Group Name: {group_name}, Total items: {total}, Total pages: {num_pages}.")
    else:
        print(f"Failed to fetch data for Group ID: {group_id}. Status code:", response.status_code)

Group Name: Nhà Sách Tiki, Total items: 2000, Total pages: 50.
Group Name: Nhà Cửa - Đời Sống, Total items: 2000, Total pages: 50.
Group Name: Điện Thoại - Máy Tính Bảng, Total items: 572, Total pages: 15.
Group Name: Đồ Chơi - Mẹ & Bé, Total items: 2000, Total pages: 50.
Group Name: Thiết Bị Số - Phụ Kiện Số, Total items: 2000, Total pages: 50.
Group Name: Điện Gia Dụng, Total items: 2000, Total pages: 50.
Group Name: Làm Đẹp - Sức Khỏe, Total items: 2000, Total pages: 50.
Group Name: Ô Tô - Xe Máy - Xe Đạp, Total items: 2000, Total pages: 50.
Group Name: Thời trang nữ, Total items: 2000, Total pages: 50.
Group Name: Bách Hóa Online, Total items: 2000, Total pages: 50.
Group Name: Thể Thao - Dã Ngoại, Total items: 2000, Total pages: 50.
Group Name: Thời trang nam, Total items: 2000, Total pages: 50.
Group Name: Cross Border - Hàng Quốc Tế, Total items: 2000, Total pages: 50.
Group Name: Laptop - Máy Vi Tính - Linh kiện, Total items: 2000, Total pages: 50.
Group Name: Giày - Dép nam, Total items: 2000, Total pages: 50.
Group Name: Điện Tử - Điện Lạnh, Total items: 2000, Total pages: 50.
Group Name: Giày - Dép nữ, Total items: 2000, Total pages: 50.
Group Name: Máy Ảnh - Máy Quay Phim, Total items: 2000, Total pages: 50.
Group Name: Phụ kiện thời trang, Total items: 2000, Total pages: 50.
Group Name: NGON, Total items: 2000, Total pages: 50.
Group Name: Đồng hồ và Trang sức, Total items: 2000, Total pages: 50.
Group Name: Balo và Vali, Total items: 2000, Total pages: 50.
Group Name: Voucher - Dịch vụ, Total items: 2000, Total pages: 50.
Group Name: Túi thời trang nữ, Total items: 2000, Total pages: 50.
Group Name: Túi thời trang nam, Total items: 2000, Total pages: 50.